Support prefixes with args
julia-actions/julia-runtest pull request #48
Opened 2021-07-17 17:23 UTC by IanButterworth

Implements @colinxs's suggestion in https://github.com/julia-actions/julia-runtest/issues/41

Fixes #41

2021-07-17 17:38 UTC, IanButterworth commented
Doesn't seem quite right yet https://github.com/IanButterworth/Example.jl/pull/1

2021-07-17 19:40 UTC, IanButterworth commented
ok, this is working over in IanButterworth/Example.jl#1 with both single prefixes and prefixes with arguments

Is use of `eval` like this ok?

cc. @giordano

2022-01-07 23:47 UTC, Octogonapus commented
Bumping this so that https://github.com/julia-actions/julia-buildpkg/pull/16 can eventually get merged.

2022-01-08 00:53 UTC, IanButterworth commented
@SaschaMann 🙏🏻

2022-07-22 09:47 UTC, SaschaMann requested changes

2022-07-22 09:47 UTC, SaschaMann commented on action.yml
> +        julia_cmd="julia --color=yes --depwarn=${{ inputs.depwarn }} --inline=${{ inputs.inline }} --project=${{ inputs.project }} -e 'import Pkg;include(joinpath(ENV[\"GITHUB_ACTION_PATH\"], \"kwarg
Sorry I forgot about this for so long.

My understanding of bash is that for commands like this, parantheses should be used. The if/then block below deals with the main issue we ran into before when using double quotes but there might be other unintentional consequences I'm not aware of. So I'd prefer to stick to the best practice that was recommended back then rather switching to double quotes.

The second suggestion in #41 seems like it should work without going back to double quotes.

2022-10-27 14:44 UTC, lassepe commented
May I carefully bump this PR? I could really use this feature in a range of package CIs. Seems like it's only a small change away from being mergeable.

2023-01-08 20:48 UTC, closed without merging